var coffee, express, gulp, gutil, path, watch;

gulp = require('gulp');

coffee = require('gulp-coffee');

watch = require('gulp-watch');

gutil = require('gulp-util');

express = require('express');

path = require('path');

gulp.task('server', function() {
  var app;
  app = express();
  app.use(express["static"](path.join(__dirname, 'dist')));
  return app.listen(3000);
});

gulp.task('production-server', function() {
  var app;
  app = express();
  app.use(express["static"](path.join(__dirname, 'dist')));
  return app.listen(80);
});

gulp.task('html', function() {
  return gulp.src('./src/views/*.html').pipe(coffee({
    bare: true
  }).on('error', gutil.log)).pipe(gulp.dest('./dist/'));
});

gulp.task('coffee', function() {
  return gulp.src('./src/coffee/*.coffee').pipe(coffee({
    bare: true
  }).on('error', gutil.log)).pipe(gulp.dest('./dist/js/'));
});

gulp.task('watch', function() {
  return watch('./src/coffee/*.coffee', function(events, done) {
    return gulp.start('coffee', done);
  });
});

if (process.env.PRODUCTION) {
  gulp.task('default', ['coffee', 'watch', 'production-server']);
} else {
  gulp.task('default', ['coffee', 'watch', 'server']);
}

// ---
// generated by coffee-script 1.9.2